# alertmanager-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname']
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'email'

    receivers:
      - name: 'email'
        email_configs:
          - to: '22520217@gm.uit.edu.vn'
            from: 'datnpt2004@gmail.com'
            smarthost: 'smtp.gmail.com:587'
            auth_username: 'datnpt2004@gmail.com'
            auth_password: 'rtxn hllh bamg fnch'
            require_tls: true
