apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-rules
data:
  alert-rules.yaml: |
    groups:
      - name: alert-rules
        rules:
          - alert: HighRequestRate
            expr: nginx_ingress_nginx_http_requests_total{instance="192.168.10.201:10254"} > 200
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "High Requests"
              description: "Số lượng request vượt 200 request/phút."

          - alert: LowCPU
            expr: (1 - avg(rate(node_cpu_seconds_total[5m]))) < 0.2
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Low CPU"
              description: "CPU của container {{ $labels.container }} dưới 20%."

          - alert: LowMemory
            expr: (1 - avg(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100)) < 0.2
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Low memory"
              description: "Memory của container {{ $labels.container }} dưới 20%."
