apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'datnpt2004@gmail.com'
      smtp_auth_username: 'datnpt2004@gmail.com'
      smtp_auth_password: 'rtxn hllh bamg fnch'

    route:
      receiver: 'email-alerts'
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h

    receivers:
      - name: 'email-alerts'
        email_configs:
          - to: 'recipient-email@example.com'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.22.2
        args:
          - "--config.file=/etc/alertmanager/alertmanager.yaml"
        volumeMounts:
          - name: config-volume
            mountPath: /etc/alertmanager
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-config
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  selector:
    app: alertmanager
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
  type: ClusterIP
